#!/bin/bash

#docker buildx build --no-cache --load -t nek:latest .
 docker buildx build --platform linux/arm64 --load -t nek:latest .
#docker buildx build --platform linux/amd64 --load -t nek:latest .
